### ISSUE TITLE
[FEATURE] Use pip to install CMake in Dockerfile

### ISSUE THREAD

**Issue by arecarn** [filipdutescu/modern-cpp-template#13]
**Is your feature request related to a problem? Please describe.**
This is not really a problem, but you may not have to manually install cmake from source in the Dockerfile

**Describe the solution you'd like**
You can install cmake via pip

**Describe alternatives you've considered**
N/A

**Provide usage examples**
e.g. `pip3 install cmake`

**Additional context**
https://cmake-python-distributions.readthedocs.io/en/latest/index.html

**Comment by filipdutescu** [comment]
First of all, thank you very much for your suggestion! I did not know that was an option actually, so cheers for teaching me something new.

Second of all, while I share your view of not building CMake from source, this is only due to using Ubuntu 18.04, which has a CMake version lower than 3.15. The reason I will not fix it, is that I plan to switch to Ubuntu 20 with the next release, which would eliminate the issue.

Does this seem reasonable to you? If you still think there is a better approach, we can further discuss this matter.

**Comment by arecarn** [comment]
Seems good to me. I just shared in case it was any help to you.

**Comment by filipdutescu** [comment]
Much obliged! If you have any other suggestions, please feel free to open an issue anytime!
