### ISSUE TITLE
[BUG] CMakeLists.txt source files and header files do not print as list

### ISSUE THREAD

**Issue by NickHAnderson019** [filipdutescu/modern-cpp-template#29]
**Describe the bug**
In the projects `CMakeLists.txt`, there are calls to:

* `verbose_message(${sources})`
* `verbose_message(${exe_sources})`
* `verbose_message(${headers})`

where the variables are lists set in `SourcesAndHeaders.cmake`. 

However, when the messages are displayed in the console, only the first file is displayed in the list. E.g. if you have multiple sources, only the first file will be displayed. 

**To Reproduce**

1. Add multiple source files or header files
2. Build

**Expected behavior**
Should display all the values in a list.

**Comment by NickHAnderson019** [comment]
After doing some digging, I found a pretty trivial solution [on SO](https://stackoverflow.com/questions/17666003/cmake-output-a-list-with-delimiters). 

Instead of:
`verbose_message(${sources})`
Enclose the variable in inverted commas:
`verbose_message("${sources}")`

This isn't perfect since it doesn't print with delimiters (despite what the SO post says), but instead prints it as one long string.

**Comment by filipdutescu** [comment]
Hello! Thank you a lot for submitting this issue. I was also working with the second solution, as, for me, it seems like the better of the two. With a check before so we don't go through the `foreach` loop if verbose messaging is toggled off.

I would also like to extend my gratitude for your kindness of wishing to submit a PR. Since I have some free time at the moment, I will make the fix now, but, please, feel free to submit any PRs you would wish and I will look over them. Once I push the commit I will let you know, so you can confirm it fixes it on your end as well.

**Comment by filipdutescu** [comment]
Done, pushed the fix. Please confirm it works, whenever you can, or reopen if it doesn't. Thanks again!
