### ISSUE TITLE
[FEATURE] Control which changes trigger github actions

### ISSUE THREAD

**Issue by php1ic** [filipdutescu/modern-cpp-template#3]
**Is your feature request related to a problem? Please describe.**
Typo fixes in one of the *.md files will rerun the entire CI pipeline. Depending on how long the pipeline takes to run, this may become an issue.

**Describe the solution you'd like**
Control what triggers the CI pipeline via [config](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).

**Describe alternatives you've considered**
Github actions [doesn't seem to support](https://github.community/t/github-actions-does-not-respect-skip-ci/17325) skipping via a keyword in the commit message, so not sure there is an alternative.

**Provide usage examples**
See documentation link above

**Additional context**
I would create a PR, but I don't know if you want to implement a whilelist or a blacklist.

**Comment by filipdutescu** [comment]
@php1ic sensible request. Ideally, you would have a separate branch (dev branch) which would then be merged with the master after multiple commits, but I understand the concern.

Since one might also want to run `.sh`, `.py` etc.  on each change, I think the best approach would be to have a blacklist implementation, exempting `.md` files, for example.

I can look more into GitHub actions triggers, to ensure commit messages could or could not be used to stop triggering CI. If you wish, due to me getting to it only later today, you could also make a PR, which I will review.

Thank you for your feedback!

**Comment by Zethson** [comment]
> @php1ic sensible request. Ideally, you would have a separate branch (dev branch) which would then be merged with the master after multiple commits, but I understand the concern.

I agree. (This is also Cookietemples default behavior. When a new project from a template is created a development branch is also created).
However, I still think that @php1ic brings up a nice point. You may not care if your repository is public, since you get CI for free, but it does matter for private repos. 

I would like to second the blacklisting.

@filipdutescu Note however that your blacklist will change anyways since you will then blacklist the docs folder and rst files soon. So you can play around with it and later we can very easily change that.

**Comment by filipdutescu** [comment]
> However, I still think that @php1ic brings up a nice point. You may not care if your repository is public, since you get CI for free, but it does matter for private repos. 

Yes, I am in favour of this addition, which would help those having private repos.

> @filipdutescu Note however that your blacklist will change anyways since you will then blacklist the docs folder and rst files soon. So you can play around with it and later we can very easily change that.

Does not seem too hard to include more file types in the blacklist, afterall I do not need to specify the file name (from my current understanding). There might also be a way to hse commit messages, but, as @php1ic mentioned, it is not standardized in GH Actions atm. Do you have any knowledge of such capabilities?

**Comment by Zethson** [comment]
I would keep it simple. Just ignore md or rst files for building and testing the project.
Cookietemple actually has a workflow for building the documentation. This could then work the other way around by only building when rst or png or jpg files have been edited.  Wednesday, 03 June 2020, 03:27PM +02:00 from Filip Dutescu  notifications@github.com :

**Comment by filipdutescu** [comment]
@php1ic , @Zethson manage to fix the CI skipping with actual CI skipping.

## Added CI Skipping
In your commit message, add `[skip ci]` or `[ci skip]` in order to not run workflows for the particular commit.

I.e.:
````bash
git commit -m "my normal commit message [skip ci]"
````
